commanddetails_index:
    path:     /
    defaults: { _controller: "AppBundle:CommandDetails:index" }
    methods:  GET

commanddetails_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CommandDetails:show" }
    methods:  GET

commanddetails_new:
    path:     /new
    defaults: { _controller: "AppBundle:CommandDetails:new" }
    methods:  [GET, POST]

commanddetails_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CommandDetails:edit" }
    methods:  [GET, POST]

commanddetails_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CommandDetails:delete" }
    methods:  DELETE
