user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE

user_login:
    path: /login
    defaults: { _controller: "AppBundle:User:login" }
    methods: GET

user_login_check:
    path: /login_check
    defaults: { _controller: "AppBundle:User:login" }

user_logout:
    path: /logout
    defaults: { _controller: "AppBundle:User:login" }

user_register:
    path: /register
    defaults: { _controller: "AppBundle:User:registerCheck" }
    methods: POST
